<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'attribute' => 'Attribut',
    'checkboxes' => 'Checkboxen',
    'copy_an_attribute' => 'Attribut kopieren',
    'created_at' => 'Erstellt am',
    'created_by' => 'Erstellt von',
    'dropdown_select' => 'Auswahlmenü',
    'email_intro' => 'E-Mail-Einleitung',
    'file' => 'Datei',
    'form' => 'Formular',
    'form_id' => 'Formular-ID',
    'formatting' => 'Formatierung',
    'hint' => 'Hinweis',
    'id' => 'ID',
    'is_done' => 'Erledigt',
    'label' => 'Beschriftung',
    'language' => 'Sprache',
    'multiline_input' => 'Mehrzeiliges Eingabefeld',
    'preview' => 'Vorschau',
    'radio_list' => 'Radiobutton-Liste',
    'recipients' => 'Empfänger',
    'required' => 'Erforderlich',
    'row_template' => 'Zeilen-Vorlage',
    'select' => 'Auswählen',
    'subject' => 'Betreff',
    'submission_id' => 'Übermittlungs-ID',
    'success' => 'Erfolg',
    'summary' => 'Zusammenfassung',
    'text' => 'Text',
    'title' => 'Titel',
    'type' => 'Typ',
    'updated_at' => 'Aktualisiert am',
    'updated_by' => 'Aktualisiert von',
    'url' => 'URL',
    'useragent' => 'Browser',
    'validation_rule' => 'Validierungsregel',
    'value' => 'Wert',
    'values' => 'Werte',
    'variables_available' => 'Die Variablen {{label}} und {{value}} sind verfügbar.',
    'checkboxes_values_help' => 'Wenn nur ein Wert gesetzt wird, wird eine einzige Checkbox erstellt.',
    'form_label_previewBackButtonLabel' => 'Beschriftung Zurück-Button der Vorschau',
    'form_label_previewButtonsTemplate' => 'Vorlage für den Weiter- und Zurück-Button der Vorschau',
    'form_label_previewSubmitButtonLabel' => 'Beschriftung Weiter-Button der Vorschau',
    'form_label_submitButtonLabel' => 'Beschriftung Weiter-Button des Formulars',
    'form_model_copy_to_attribute_hint' => 'Wenn definiert und das Attribut im Formular vorhanden ist, wird der Wert des angegebenen Felds zu der Empfänger-Liste hinzugefügt.',
    'form_model_email_intro_hint' => 'Wenn definiert, wird der Wert verwendet für die E-Mail-Einleitung. Alle definierten Variabeln können mittels {{attribute}} eingefügt werden.',
    'form_model_subject_hint' => 'Betreff des E-Mails. Wenn nichts angegeben wird, wird der Titel des Formulars verwendet.',
];
