<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Attribute' => 'Attribut',
    'Automatically' => 'Automatisch',
    'Boolean (Yes/No)' => 'Boolean (Ja/Nein)',
    'Checkboxes' => 'Checkboxen',
    'Copy to Attribute' => 'Empfänger Attribut-Name',
    'Created At' => 'Erstellt am',
    'Created By' => 'Erstellt von',
    'Created at' => 'Erstellt am',
    'Customizing Text' => 'E-Mail Texte Anpassen',
    'Date' => 'Datum',
    'Date & Time' => 'Datum & Zeit',
    'Dropdown Select' => 'Dropdown Auswahl',
    'E-Mail Recipients' => 'Empfänger',
    'E-Mail intro' => 'Einleitungstext',
    'E-Mail outro' => 'Fusstext',
    'Email' => 'E-Mail',
    'Everything allowed' => 'Alle Werte sind erlaubt',
    'Export' => 'Exportieren',
    'File' => 'Datei',
    'Form' => 'Formular',
    'Form ID' => 'Formular-ID',
    'Formatting' => 'Formatierung',
    'Generate Export' => 'Export generieren',
    'Hint' => 'Hinweis',
    'ID' => 'ID',
    'Is Done' => 'Erledigt',
    'Is done' => 'Erledigt',
    'Label' => 'Beschriftung',
    'Language' => 'Sprache',
    'Multiline Input' => 'Mehrzeiliges Eingabefeld',
    'Number' => 'Nummer',
    'Preview' => 'Vorschau',
    'Preview data' => 'Vorschau der Daten',
    'Radio List' => 'Radiobutton-Liste',
    'Recipients' => 'Empfänger',
    'Required' => 'Erforderlich',
    'Row Template' => 'Zeilen-Vorlage',
    'String' => 'Text',
    'Subject' => 'Betreff',
    'Submission ID' => 'Übermittlungs-ID',
    'Submissions' => 'Eingaben',
    'Success' => 'Erfolg',
    'Summary' => 'Zusammenfassung',
    'Text' => 'Text Eingabe',
    'The variables {{label}} and {{value}} are available.' => 'Die Variablen {{label}} und {{value}} sind verfügbar.',
    'There are no submissions to export.' => 'Es gitb keine Daten zu exportieren.',
    'Title' => 'Titel',
    'Type' => 'Typ',
    'Updated At' => 'Aktualisiert am',
    'Updated By' => 'Aktualisiert von',
    'Url' => 'URL',
    'Useragent' => 'Browser',
    'Validation Rule' => 'Validierungsregel',
    'Value' => 'Wert',
    'Values' => 'Werte',
    'checkboxes_values_help' => 'Wenn nur ein Wert gesetzt wird, wird eine einzige Checkbox erstellt.',
    'form_label_previewBackButtonLabel' => 'Beschriftung Zurück-Button der Vorschau',
    'form_label_previewButtonsTemplate' => 'Vorlage für den Weiter- und Zurück-Button der Vorschau',
    'form_label_previewSubmitButtonLabel' => 'Beschriftung Weiter-Button der Vorschau',
    'form_label_submitButtonLabel' => 'Beschriftung Übermitteln-Button des Formulars',
    'form_model_copy_to_attribute_hint' => 'Wenn das Attribut definiert wurde und im Formular vorhanden ist, wird sein Wert zu der Empfänger-Liste hinzugefügt.',
    'form_model_email_intro_hint' => 'Der Text dieses Felds wird als Einleitungstext der E-Mail verwendet. Alle definierten Variabeln können mittels {{attribute}} eingefügt werden.',
    'form_model_subject_hint' => 'Betreff der E-Mail. Wenn nichts angegeben wird, wird der Titel des Formulars verwendet.',
    'Boolean' => '',
    'Browser' => '',
    'Data' => 'Daten',
    'Forms' => 'Formulare',
    'Setup' => 'Einrichten',
    'Submission' => 'Eingaben',
];
