<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Attribute' => '',
    'Checkboxes' => '',
    'Copy an Attribute' => '',
    'Created At' => '',
    'Created By' => '',
    'Dropdown Select' => '',
    'E-Mail intro' => '',
    'File' => '',
    'Form' => '',
    'Form ID' => '',
    'Formatting' => '',
    'Hint' => '',
    'ID' => '',
    'Is Done' => '',
    'Label' => '',
    'Language' => '',
    'Multiline Input' => '',
    'Preview' => '',
    'Radio List' => '',
    'Recipients' => '',
    'Required' => '',
    'Row Template' => '',
    'Select' => '',
    'Subject' => '',
    'Submission ID' => '',
    'Success' => '',
    'Summary' => '',
    'Text' => '',
    'Title' => '',
    'Type' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Url' => '',
    'Useragent' => '',
    'Validation Rule' => '',
    'Value' => '',
    'Values' => '',
    'Variables {{label}} and {{value}} are available' => '',
    'checkboxes_values_help' => '',
    'form_label_previewBackButtonLabel' => '',
    'form_label_previewButtonsTemplate' => '',
    'form_label_previewSubmitButtonLabel' => '',
    'form_label_submitButtonLabel' => '',
    'form_model_copy_to_attribute_hint' => '',
    'form_model_email_intro_hint' => '',
    'form_model_subject_hint' => '',
];
