<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Copy to Attribute' => 'Recipients attribute name',
    'Customizing Text' => 'Customizing E-Mail Text',
    'Form' => 'Form',
    'Values' => 'Values',
    'checkboxes_values_help' => 'If only one value is specified, a single checkbox will be created.',
    'form_label_previewBackButtonLabel' => 'Label of back button of preview',
    'form_label_previewButtonsTemplate' => 'Template for next and back button of preview',
    'form_label_previewSubmitButtonLabel' => 'Label of next button of preview',
    'form_label_submitButtonLabel' => 'Label of submit button of form',
    'form_model_copy_to_attribute_hint' => 'If the attribute is specified and exists in the form, its field\'s value will be added to the list of recipients.',
    'form_model_email_intro_hint' => 'The text of this field will be used as an intro text for the email. All specified variables can be inserted with {{attribute}}.',
    'form_model_subject_hint' => 'Subject of the e-mail. If not specified, the title of the form will be used.',
    'Attribute' => '',
    'Automatically' => '',
    'Back' => '',
    'Boolean' => '',
    'Boolean (Yes/No)' => '',
    'Browser' => '',
    'Checkboxes' => '',
    'Created At' => '',
    'Created By' => '',
    'Created at' => '',
    'Date' => '',
    'Date & Time' => '',
    'Dropdown Select' => '',
    'E-Mail Recipients' => '',
    'E-Mail intro' => '',
    'E-Mail outro' => '',
    'Email' => '',
    'Everything allowed' => '',
    'Export' => '',
    'File' => '',
    'Form ID' => '',
    'Formatting' => '',
    'Generate Export' => '',
    'Hint' => '',
    'ID' => '',
    'Image' => '',
    'Is Done' => '',
    'Is done' => '',
    'Label' => '',
    'Language' => '',
    'Multiline Input' => '',
    'Multiline Text' => '',
    'Number' => '',
    'Preview' => '',
    'Preview data' => '',
    'Radio List' => '',
    'Recipients' => '',
    'Required' => '',
    'Row Template' => '',
    'String' => '',
    'Subject' => '',
    'Submission ID' => '',
    'Submissions' => '',
    'Submit' => '',
    'Success' => '',
    'Summary' => '',
    'Text' => '',
    'The variables {{label}} and {{value}} are available.' => '',
    'There are no submissions to export.' => '',
    'This form block is not properly configured. Select a form from the listing in the block settings.' => '',
    'Title' => '',
    'Type' => '',
    'URL/Link' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Url' => '',
    'Useragent' => '',
    'Validation Rule' => '',
    'Value' => '',
    'Data' => 'Data',
    'Format' => '',
    'Forms' => 'Forms',
    'No validation specific' => '',
    'Setup' => 'Setup',
    'Submission' => 'Submission',
];
