<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Confirmation Step' => 'Mostrar resumo',
    'Copy to Attribute' => 'Nome do atributo do destinatário',
    'Customizing Text' => 'Personalizando o texto do e-mail',
    'Form' => 'Formulário',
    'Values' => 'Valores',
    'checkboxes_values_help' => 'Se apenas um valor for especificado, uma única caixa de seleção será criada.',
    'form_label_previewBackButtonLabel' => 'Rótulo do botão Voltar da visualização',
    'form_label_previewButtonsTemplate' => 'Template for next and back button of preview',
    'form_label_previewSubmitButtonLabel' => 'Modelo para o botão próximo e voltar da visualização',
    'form_label_submitButtonLabel' => 'Rótulo do botão enviar do formulário',
    'form_model_copy_to_attribute_hint' => 'Se o atributo for especificado e existir no formulário, o valor de seu campo será adicionado à lista de destinatários.',
    'form_model_email_intro_hint' => 'O texto deste campo será usado como texto de introdução para o e-mail. Todas as variáveis ​​especificadas podem ser inseridas com {{attribute}}.',
    'form_model_email_recipients_hint' => 'Se nenhum destinatário for fornecido, o envio do formulário não acionará um e-mail.',
    'form_model_subject_hint' => 'Assunto do e-mail. Se não for especificado, o título do formulário será usado.',
    'As Hidden Input Value' => 'Como valor de input oculto',
    'Attribute' => 'Atributo',
    'Automatically' => 'Automaticamente',
    'Back' => 'Voltar',
    'Boolean' => 'Boleano',
    'Boolean (Yes/No)' => 'Boleano (Sim/Não)',
    'Checkboxes' => 'Checkboxes', // no need translation for this
    'Created At' => 'Criado em',
    'Created By' => 'Criado por',
    'Date' => 'Data',
    'Date & Time' => ' Data & Hora',
    'Datepicker' => 'Selecionador de data',
    'Disable Polyfill' => 'Desabilitar Polyfill',
    'Do not save data' => 'Não salvar os dados',
    'Dropdown' => 'Dropdown', // no need translation
    'Dropdown/Radio Buttons' => 'Dropdown/Botão Radio',
    'E-Mail Recipients' => 'Destinatários de e-email',
    'E-Mail intro' => 'Introdução do e-mail',
    'E-Mail outro' => 'Outras informações do e-mail',
    'Email' => 'Email',
    'Everything allowed' => 'Permissão total',
    'Export' => 'Exportar',
    'File' => 'Arquivo',
    'Form ID' => 'ID do Formulário',
    'Formatting' => 'Formatando',
    'Generate Export' => 'Gerar Exportação',
    'Hint' => 'Dica',
    'ID' => 'ID',
    'If enabled, the form data will not be stored in the database, but only sent by e-mail to the specified recipients.' => 'Se habilitado, o formulário não será armazenado no banco de dados, será somente enviado por e-mail para os destinatários especificados',
    'Image' => 'Imagem',
    'Is Done' => 'Feito',
    'Label' => 'Etiqueta',
    'Language' => 'Idioma',
    'Multiline Input' => 'Input com múltiplas linhas',
    'Multiline Rows' => 'Fileira com múltiplas linhas',
    'Multiline Text' => 'Texto com multiplas linhas',
    'Number' => 'Número',
    'Preview' => 'Visualizar',
    'Radio Buttons' => 'Botões Radio',
    'Recipients' => 'Destinatários',
    'Required' => 'Requerido',
    'Row Template' => 'Template da fileira',
    'Select the formular configuraton (defining mail and other settings) from the database or create a new one.' => 'Selecione a configuração do formulário (definindo correio e outras configurações) do banco de dados ou crie um novo.',
    'Separator' => 'Separador',
    'String' => 'String',
    'Subject' => 'Assunto',
    'Submission ID' => 'ID do envio', 
    'Submissions' => 'Envios',
    'Submit' => 'Enviar',
    'Success' => 'Sucesso',
    'Summary' => 'Resumo',
    'Text' => 'Texto',
    'The HTML code that separates items. By default, it is a newline, use &nbsp; to separate items with spaces.' => 'O código HTML que separa os itens. Por padrão, é uma nova linha, use &nbsp; para separar itens com espaços.',
    'The variables {{label}} and {{value}} are available.' => 'As variáveis {{label}} e {{value}} estão disponíveis.',
    'There are no submissions to export.' => 'Não há envios para exportação.',
    'This form block is not properly configured. Select a form from the listing in the block settings.' => 'Este bloco de formulário não está configurado corretamente. Selecione um formulário da lista nas configurações do bloco.',
    'Title' => 'Título',
    'Type' => 'Tipo',
    'URL/Link' => 'URL/Link', // no need translation
    'Updated At' => 'Atualizado em',
    'Updated By' => 'Atualizado por',
    'Url' => 'Url', // no need translation
    'Useragent' => 'Useragent', // no need translation
    'Validation Rule' => 'Regra de validação',
    'Value' => 'Valor',
    'When enabled, the polyfill which ensures the datepicker works on Safari and Internet Explorer is disabled.' => 'Quando ativado, o polyfill que garante que o selecionador de data funcione no Safari e no Internet Explorer é desativado',
    'When enabled, the user will be presented with a summary before submitting the form data.' => 'Quando habilitado, o usuário receberá um resumo antes de enviar os dados do formulário.',
    'block_hiddenInputValue_help' => 'Se este campo contiver um valor, ele ficará oculto e o valor especificado será enviado em vez de uma entrada do usuário. Nota: 0 não é um valor permitido.',
    'Browser' => 'Navegador',
    'Created at' => 'Criado em',
    'Data' => 'Dados',
    'Format' => 'Formato',
    'Forms' => 'Formulários',
    'Is done' => 'Feito',
    'No validation specific' => 'Nenhuma validação específica',
    'Preview data' => 'Visualizar dados',
    'Setup' => 'Configurar',
    'Submission' => 'Envio',
];
